# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='iot.proto',
  package='iot',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tiot.proto\x12\x03iot\"\x1a\n\x0bRegisterCmd\x12\x0b\n\x03\x63md\x18\x01 \x01(\r\"+\n\x0cRegisterResp\x12\x0e\n\x06status\x18\x01 \x01(\r\x12\x0b\n\x03uID\x18\x02 \x01(\r2J\n\x0eMachineControl\x12\x38\n\x0fRegisterMachine\x12\x10.iot.RegisterCmd\x1a\x11.iot.RegisterResp\"\x00\x62\x06proto3'
)




_REGISTERCMD = _descriptor.Descriptor(
  name='RegisterCmd',
  full_name='iot.RegisterCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='iot.RegisterCmd.cmd', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=44,
)


_REGISTERRESP = _descriptor.Descriptor(
  name='RegisterResp',
  full_name='iot.RegisterResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='iot.RegisterResp.status', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uID', full_name='iot.RegisterResp.uID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['RegisterCmd'] = _REGISTERCMD
DESCRIPTOR.message_types_by_name['RegisterResp'] = _REGISTERRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterCmd = _reflection.GeneratedProtocolMessageType('RegisterCmd', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERCMD,
  '__module__' : 'iot_pb2'
  # @@protoc_insertion_point(class_scope:iot.RegisterCmd)
  })
_sym_db.RegisterMessage(RegisterCmd)

RegisterResp = _reflection.GeneratedProtocolMessageType('RegisterResp', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERRESP,
  '__module__' : 'iot_pb2'
  # @@protoc_insertion_point(class_scope:iot.RegisterResp)
  })
_sym_db.RegisterMessage(RegisterResp)



_MACHINECONTROL = _descriptor.ServiceDescriptor(
  name='MachineControl',
  full_name='iot.MachineControl',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=91,
  serialized_end=165,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterMachine',
    full_name='iot.MachineControl.RegisterMachine',
    index=0,
    containing_service=None,
    input_type=_REGISTERCMD,
    output_type=_REGISTERRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MACHINECONTROL)

DESCRIPTOR.services_by_name['MachineControl'] = _MACHINECONTROL

# @@protoc_insertion_point(module_scope)
